//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Plataforma para Coordinadores y Alumnos.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG_GENE                 103
#define IDD_DIALOG_ReCarre              105
#define IDD_DIALOG_Crear_SEM            107
#define IDD_DIALOG_RegiMate             109
#define IDR_MENU1                       111
#define IDD_DIALOG_CooCarr              112
#define IDD_VerCooCarrWindow            114
#define IDR_MENU2                       116
#define IDD_DIALOG2                     117
#define IDD_Consulta_Materias           117
#define IDD_D_Regi_Alum                 119
#define IDD_D_Asig_Masiva               121
#define IDD_Calif                       123
#define IDD_ALUM_MATE                   125
#define IDD_MATE_ALUM                   127
#define IDD_Kardex                      129
#define IDD_Listas_Clases               131
#define IDC_STATIC_01                   1001
#define IDC_COMBO1                      1002
#define IDC_STATIC_3                    1002
#define IDC_EDIT1                       1003
#define IDC_STATIC_4                    1003
#define IDC_COMBO_M01                   1003
#define IDC_EDIT2                       1004
#define IDC_EDIT8                       1005
#define IDC_STATIC_iz                   1006
#define IDC_EDIT3                       1006
#define IDC_EDIT9                       1006
#define IDC_STATIC_de                   1007
#define IDC_EDIT4                       1007
#define IDC_ENTRAR_MAIN                 1008
#define IDC_B_Registro_de_Carreras      1009
#define IDC_EDIT5                       1009
#define IDC_STATIC_aux                  1009
#define IDC_NAME_GENE                   1010
#define IDC_EDIT6                       1010
#define IDC_EDIT7                       1011
#define IDC_B_Crear_Semestre            1011
#define IDC_B_Registro_de_Materia       1012
#define IDC_FOTO_GENE                   1013
#define IDC_BUTTON_Guardar_Informacion  1015
#define IDC_RADIO1                      1018
#define IDC_RADIO2                      1019
#define IDC_Buttor_confirmation_SEM     1021
#define IDC_BUTTON_Regi_Mate            1022
#define IDC_EDIT_aux                    1023
#define IDC_Edit_Photo                  1024
#define IDC_EDIT_aux2                   1025
#define IDC_Pho_CooCarr                 1026
#define IDC_STATIC_name_cc              1027
#define IDC_STATIC_photo                1029
#define IDC_CooCar_Photo                1030
#define IDC_STATIC_carr_cc              1030
#define IDC_Clave                       1032
#define IDC_Siglas                      1033
#define IDC_Descripcion                 1034
#define IDC_Nombre                      1035
#define IDC_Usuario                     1036
#define IDC_Password                    1037
#define IDC_CooCar_Photo_2              1038
#define IDC_COMBO_aux                   1039
#define IDC_Captura_Calif               1040
#define IDC_Alta                        1041
#define IDC_InscAlumn                   1042
#define IDC_LIST1                       1043
#define IDC_LIST_unic                   1043
#define IDC_LIST_ALUMN                  1043
#define IDC_LIST_KARDEX                 1043
#define IDC_LIST_Clase                  1043
#define IDC_BU_Edi                      1044
#define IDC_LIST_ALUMN_SELECCION        1044
#define IDC_BUTTON2                     1045
#define IDC_BU_Gu_Ca                    1045
#define IDC_Boton_Busca                 1045
#define IDC_Aceptar                     1045
#define IDC_STATIC101                   1046
#define IDC_BU_Borrar                   1046
#define IDC_STATIC4                     1047
#define IDC_BU_Borrar_M                 1047
#define IDC_STATIC5                     1048
#define IDC_STATIC6                     1049
#define IDC_B_Registrar_Alumno          1049
#define IDC_STATIC7                     1050
#define IDC_STATIC_Carrera              1050
#define IDC_BUTTON_Alum_A_Mate          1051
#define IDC_BUTTON_Mate_A_Alum          1052
#define IDC_Alum_A_Mate                 1053
#define IDC_Mate_A_Alum                 1054
#define IDC_EDIT10                      1055
#define IDC_EDIT11                      1056
#define IDC_EDIT19                      1058
#define IDC_LIST_unic2                  1059
#define IDC_COMBO2                      1060
#define IDC_BUTTON1                     1061
#define IDC_LIST_MATE                   1062
#define IDC_LIST_MATE_SELECCION         1063
#define IDC_B_INSCRI                    1064
#define IDC_EDIT_MATRICUAL              1065
#define IDC_STATIC_NAME                 1066
#define IDC_COMBO_S01                   1067
#define ID_OPCIONES_ATRAS               40001
#define ID_OPCIONES_Regresar            40002
#define ID_OPCIONES_SALIRYGUARDAR       40003
#define ID_VER_VERTODOSLOSCOORDINADORESREGISTRADOS 40004
#define ID_ALUMNOS_VERTODOS             40005
#define ID_VER_TODASLASMATERIASREGISTRADAS 40006
#define ID_OPCIONES                     40007
#define ID_MATERIAS                     40008
#define ID_OPCIONES_REGRESAR            40009
#define ID_OPCIONES_GUARDARYSALIR       40010
#define ID_CONSULTAS_LISTASDECLASE      40011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
